import "server-only";

import type { SanityClient } from "next-sanity";

import type { ScrapedMatch } from "./profixio";

const ARRIVAL_MINUTES_BEFORE = 30;

type Inputs = {
  client: SanityClient;
  match: ScrapedMatch;
  matchDocId: string;
};

export async function ensureMeetingEntry({ client, match, matchDocId }: Inputs): Promise<string | null> {
  const entryId = `auto-meeting-${match.externalId}`;
  const meetingTime = new Date(
    new Date(match.kickoff).getTime() - ARRIVAL_MINUTES_BEFORE * 60 * 1000,
  ).toISOString();

  const existing = await client.fetch<{ _id: string; autoGenerated?: boolean } | null>(
    `*[_id == $id][0]{ _id, autoGenerated }`,
    { id: entryId },
  );

  if (existing && existing.autoGenerated === false) {
    return existing._id;
  }

  const venueLabel = match.venueName
    ? `${match.venueName}${match.pitch ? `, bane ${match.pitch}` : ""}`
    : match.pitch
      ? `bane ${match.pitch}`
      : null;

  await client.createOrReplace({
    _id: entryId,
    _type: "scheduleEntry",
    time: meetingTime,
    type: "meeting",
    title: `Oppmøte${venueLabel ? ` – ${venueLabel}` : ""}`,
    match: { _type: "reference", _ref: matchDocId },
    autoGenerated: true,
  });

  return entryId;
}
