import { ClockIcon } from "@sanity/icons";
import { defineField, defineType } from "sanity";

export const scheduleEntry = defineType({
  name: "scheduleEntry",
  title: "Programpunkt",
  type: "document",
  icon: ClockIcon,
  fields: [
    defineField({
      name: "time",
      title: "Tidspunkt",
      type: "datetime",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "type",
      title: "Type",
      type: "string",
      options: {
        list: [
          { title: "Kamp", value: "match" },
          { title: "Oppmøte", value: "meeting" },
          { title: "Kjøring", value: "travel" },
          { title: "Måltid", value: "meal" },
          { title: "Innsjekk", value: "checkin" },
          { title: "Søvn / hvile", value: "sleep" },
          { title: "Info", value: "info" },
        ],
      },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "title",
      title: "Tittel",
      type: "string",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "match",
      title: "Tilknyttet kamp",
      type: "reference",
      to: [{ type: "match" }],
      hidden: ({ parent }) => parent?.type !== "match" && parent?.type !== "meeting",
    }),
    defineField({
      name: "venue",
      title: "Sted (bane)",
      type: "reference",
      to: [{ type: "venue" }],
    }),
    defineField({
      name: "school",
      title: "Sted (skole)",
      type: "reference",
      to: [{ type: "school" }],
    }),
    defineField({
      name: "note",
      title: "Notat",
      type: "array",
      of: [{ type: "block" }],
    }),
    defineField({
      name: "autoGenerated",
      title: "Auto-generert",
      type: "boolean",
      description: "Hvis sant, kan synkrunden overskrive eller slette dette. Sett til false hvis du har redigert manuelt.",
      initialValue: false,
    }),
  ],
  orderings: [
    {
      title: "Tid (stigende)",
      name: "timeAsc",
      by: [{ field: "time", direction: "asc" }],
    },
  ],
  preview: {
    select: { title: "title", time: "time", type: "type" },
    prepare: ({ title, time, type }) => {
      const t = time
        ? new Date(time).toLocaleString("nb-NO", {
            weekday: "short",
            hour: "2-digit",
            minute: "2-digit",
          })
        : "?";
      return { title, subtitle: `${t} · ${type}` };
    },
  },
});
