import { defineQuery } from "next-sanity";

export const siteSettingsQuery = defineQuery(`
  *[_type == "siteSettings"][0]{
    title,
    clubName,
    "logoUrl": logo.asset->url,
    primaryColor,
    accentColor,
    contactName,
    contactPhone,
    contactEmail
  }
`);

export const tournamentQuery = defineQuery(`
  *[_type == "tournament"][0]{
    name,
    ourTeamName,
    groupName,
    category,
    startDate,
    endDate,
    intro,
    "accommodation": accommodation->{ _id, name, address, checkInTime, checkOutTime, rules, packingList }
  }
`);

export const ourMatchesQuery = defineQuery(`
  *[_type == "match" && weAre in ["home", "away"]] | order(kickoff asc){
    _id,
    externalId,
    status,
    kickoff,
    homeTeam,
    awayTeam,
    weAre,
    pitch,
    homeScore,
    awayScore,
    groupName,
    "venue": venue->{ name, shortName }
  }
`);

export const groupMatchesQuery = defineQuery(`
  *[_type == "match" && groupName == $groupName] | order(kickoff asc){
    _id,
    externalId,
    status,
    kickoff,
    homeTeam,
    awayTeam,
    weAre,
    pitch,
    homeScore,
    awayScore,
    "venue": venue->{ name, shortName }
  }
`);

export const scheduleQuery = defineQuery(`
  *[_type == "scheduleEntry"] | order(time asc){
    _id,
    time,
    type,
    title,
    autoGenerated,
    note,
    "match": match->{
      _id,
      kickoff,
      homeTeam,
      awayTeam,
      weAre,
      pitch,
      homeScore,
      awayScore,
      status,
      "venue": venue->{ name, shortName }
    },
    "venue": venue->{ name, shortName, address },
    "school": school->{ name, address }
  }
`);

export const schoolQuery = defineQuery(`
  *[_type == "school"] | order(_createdAt asc)[0]{
    _id,
    name,
    address,
    checkInTime,
    checkOutTime,
    rules,
    packingList
  }
`);

export const playersQuery = defineQuery(`
  *[_type == "player"] | order(shirtNumber asc, name asc){
    _id,
    name,
    shirtNumber,
    position,
    parents[]{ name, phone, email, carSeats }
  }
`);

export const latestSyncQuery = defineQuery(`
  *[_type == "syncLog"] | order(timestamp desc)[0]{
    _id,
    timestamp,
    status,
    summary,
    matchesCreated,
    matchesUpdated
  }
`);
